# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:16-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Stage 2: Run
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy compiled code and package.json
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm install --production

# Define environment variable for config path
ENV CONFIG_PATH=/app/config.json

# Set the entry point for the container
ENTRYPOINT ["node", "dist/bin/cli.js"]
